Module11 task1
htmlacademy-javascript/2116963-keksobooking-27 pull request #10
Opened 2022-11-11 22:38 UTC by alex-v-10

2022-11-12 07:07 UTC, AlexMasterov requested changes

2022-11-12 07:07 UTC, AlexMasterov commented on d
> +  master[m
Файл `d` нужно удалить.

2022-11-12 07:07 UTC, AlexMasterov commented on js/form.js
> +
<details>
<summary>form.js</summary>

https://github.com/htmlacademy-javascript/2116963-keksobooking-27/blob/07f1f63dc21b1b12b0e46ad7ee39cdc7c81fb7a9/js/form.js#L165-L167
https://github.com/htmlacademy-javascript/2116963-keksobooking-27/blob/07f1f63dc21b1b12b0e46ad7ee39cdc7c81fb7a9/js/form.js#L172-L174
https://github.com/htmlacademy-javascript/2116963-keksobooking-27/blob/07f1f63dc21b1b12b0e46ad7ee39cdc7c81fb7a9/js/form.js#L186-L188
</details>

<details>
<summary>form.js</summary>

https://github.com/htmlacademy-javascript/2116963-keksobooking-27/blob/07f1f63dc21b1b12b0e46ad7ee39cdc7c81fb7a9/js/form.js#L193-L195
https://github.com/htmlacademy-javascript/2116963-keksobooking-27/blob/07f1f63dc21b1b12b0e46ad7ee39cdc7c81fb7a9/js/form.js#L212-L214
</details>

Много похожего кода написано повторно.


[`Д 14`](https://up.htmlacademy.ru/javascript/27/criteries#d14)
> Отсутствует дублирование кода: повторяющиеся части кода переписаны как функции

2022-11-12 07:07 UTC, AlexMasterov commented on js/form.js
> +  advertForm.addEventListener('submit', (evt) => {
const `set`OnFormSubmit = (callback) => {
  advertForm.addEventListener('submit', `(evt) => {`

Функция вместо _установки_ неявно _добавляет_ анон. обработчик, который не получится удалить. Повторный вызов такой функции приведет к их накоплению.

2022-11-12 07:07 UTC, AlexMasterov commented on js/main.js
> +
https://github.com/htmlacademy-javascript/2116963-keksobooking-27/blob/07f1f63dc21b1b12b0e46ad7ee39cdc7c81fb7a9/js/form.js#L205
https://github.com/htmlacademy-javascript/2116963-keksobooking-27/blob/07f1f63dc21b1b12b0e46ad7ee39cdc7c81fb7a9/js/main.js#L34

На защите _могут_ попросить для адресов сервера создать переменные с названием в формате "констант".

[`Б 7`](https://up.htmlacademy.ru/javascript/27/criteries#b7)
> Названия констант (постоянных значений) написаны прописными (заглавными) буквами

2022-11-12 07:07 UTC, AlexMasterov commented on js/main.js
> +
https://github.com/htmlacademy-javascript/2116963-keksobooking-27/blob/07f1f63dc21b1b12b0e46ad7ee39cdc7c81fb7a9/js/form.js#L171
https://github.com/htmlacademy-javascript/2116963-keksobooking-27/blob/07f1f63dc21b1b12b0e46ad7ee39cdc7c81fb7a9/js/form.js#L185
https://github.com/htmlacademy-javascript/2116963-keksobooking-27/blob/07f1f63dc21b1b12b0e46ad7ee39cdc7c81fb7a9/js/main.js#L20

Желательно эту проверку вынести в функцию.

[`Д 14`](https://up.htmlacademy.ru/javascript/27/criteries#d14)
> Отсутствует дублирование кода: повторяющиеся части кода переписаны как функции

2022-11-12 07:07 UTC, AlexMasterov commented on js/main.js
> +
См. ТЗ:
> Отрисовка соответствующих выбранным фильтрам меток должна происходить не чаще, чем _раз в полсекунды_ (устранение дребезга)

Если уже ознакомился с реализацией _дребезга_, то этот пункт можно попробовать доработать в этом задание.

2022-11-12 07:07 UTC, AlexMasterov commented on js/main.js
> +
<details>
<summary>Проблема</summary>

https://github.com/htmlacademy-javascript/2116963-keksobooking-27/blob/07f1f63dc21b1b12b0e46ad7ee39cdc7c81fb7a9/js/map-filters.js#L2-L6
https://github.com/htmlacademy-javascript/2116963-keksobooking-27/blob/07f1f63dc21b1b12b0e46ad7ee39cdc7c81fb7a9/js/map-filters.js#L42
</details>

![image](https://user-images.githubusercontent.com/700213/201461266-2d69eb32-e009-4f07-a91b-896cd61a4ddc.png)

Сейчас: `10000 - 49999`.

![image](https://user-images.githubusercontent.com/700213/201461410-adb395ee-416a-4742-809f-c9bb32279fba.png)

Сейчас: `до 9999`.

> По варианту `включительно` вроде было решение, но уже часто оставляют на усмотрение студента. Можно оставить на усмотрение случайного проверяющего

2022-11-12 07:07 UTC, AlexMasterov commented on js/main.js
> +
См. ТЗ:
> В объявлениях, полученных с сервера, может отсутствовать часть информации

<details>
<summary>Проблема</summary>

![image](https://user-images.githubusercontent.com/700213/201461690-f3e50207-5cc8-4280-a955-1049cc02529f.png)

</details>

При сортировки объявлений по удобствам (`features`) выбрасывается исключение (ошибка).

[`Б 2`](https://up.htmlacademy.ru/javascript/27/criteries#b2) 
> При выполнении кода не возникает необработанных ошибок

2022-11-12 07:07 UTC, AlexMasterov commented on js/main.js
> +
<details>
<summary>map-filters.js</summary>

https://github.com/htmlacademy-javascript/2116963-keksobooking-27/blob/07f1f63dc21b1b12b0e46ad7ee39cdc7c81fb7a9/js/map-filters.js#L46-L49
</details>

Лучше сразу проверить объявления на наличие выбранных удобств. Если их нет, то обращаться к DOM (браузеру) не потребуется.

2022-11-12 07:07 UTC, AlexMasterov commented on js/main.js
> +
<details>
<summary>map-filters.js</summary>

https://github.com/htmlacademy-javascript/2116963-keksobooking-27/blob/07f1f63dc21b1b12b0e46ad7ee39cdc7c81fb7a9/js/map-filters.js#L46-L53
</details>

На защите _могут_ попросить записать это условие без `if`, в одном выражение.

[`Д 18`](https://up.htmlacademy.ru/javascript/27/criteries#d18)
> Условия упрощены

2022-11-12 07:07 UTC, AlexMasterov commented on js/main.js
> +
<details>
<summary>Проблема</summary>

![image](https://user-images.githubusercontent.com/700213/201461979-9cd36f0c-1ea7-407a-941d-ca5a5d94cc46.png)
![image](https://user-images.githubusercontent.com/700213/201461984-95eb8935-75d6-44bd-8d49-41bc37f49a5f.png)

![image](https://user-images.githubusercontent.com/700213/201461970-a232e596-112c-4c33-aba5-469136d8bf22.png)

</details>

После успешной отправки объявления или сброса страницы ползунок слайдера не сбрасывается.

2022-11-12 07:33 UTC, AlexMasterov commented on js/main.js
> +    .then((adverts) => onSuccess(adverts))
```diff
- .then((adverts) => onSuccess(adverts))
+ .then(onSuccess)
```

2022-11-12 08:15 UTC, AlexMasterov commented on js/main.js
> +
<details>
<summary>main.js</summary>

https://github.com/htmlacademy-javascript/2116963-keksobooking-27/blob/07f1f63dc21b1b12b0e46ad7ee39cdc7c81fb7a9/js/main.js#L47-L49
https://github.com/htmlacademy-javascript/2116963-keksobooking-27/blob/07f1f63dc21b1b12b0e46ad7ee39cdc7c81fb7a9/js/main.js#L52-L54
https://github.com/htmlacademy-javascript/2116963-keksobooking-27/blob/07f1f63dc21b1b12b0e46ad7ee39cdc7c81fb7a9/js/main.js#L61-L62
https://github.com/htmlacademy-javascript/2116963-keksobooking-27/blob/07f1f63dc21b1b12b0e46ad7ee39cdc7c81fb7a9/js/main.js#L65-L66
</details>

Могут придраться.

[`Д 14`](https://up.htmlacademy.ru/javascript/27/criteries#d14) 
> Отсутствует дублирование кода: повторяющиеся части кода переписаны как функции

2022-11-13 21:15 UTC, alex-v-10 commented on js/main.js
> +
Перенес const checkedFeatures = housingFeatures.querySelectorAll(':checked');  в функцию setAdvertMarkers - map.js 32
Теперь обращение к DOM только при вызове функции отрисовки маркеров, а не в цикле.

2022-11-13 22:29 UTC, AlexMasterov approved these changes

2022-11-13 22:29 UTC, AlexMasterov commented on js/utils.js
> +    clearTimeout(timeoutId);
<details>
<summary>blink/renderer/core/frame/dom_timer_coordinator.cc</summary>

![image](https://user-images.githubusercontent.com/700213/201545526-e829d96e-6454-49be-81aa-d490e2846449.png)

</details>


```diff
- let timeoutId;
+ let timeoutId = 0;
```
<details>
<summary>микро-оптимизация~</summary>

```js
if (timeoutId > 0) {
  clearTimeout(timeoutId);
}
```
```js
timeoutId > 0 && clearTimeout(timeoutId);
```
</details>

2022-11-13 22:29 UTC, AlexMasterov commented on js/utils.js
> +    timeoutId = setTimeout(() => callback.apply(this, rest), timeoutDelay);
timeoutId = setTimeout(`() =>` callback.apply(`this`, rest), timeoutDelay);

<details>
<summary>debounce</summary>

https://github.com/htmlacademy-javascript/2116963-keksobooking-27/blob/f28d85e02ddfaeb2eff2ef67e10c6e861620615c/js/utils.js#L1-L7
</details>

_Неявное_ изменение значения контекста `this` у пользовательского `callback` на значение `debounce` — странное решение, которое скорее (при)несет риски, чем удобства. Проблема же в том, что в стрелочном определение (= `() =>`) самой функции `debounce` значение `this` всегда будет `undefined`, и вызывающая сторона не сможет это изменить через `.call`, `.apply` и т.п.

Наличие `this` имело бы смысл в случае декларативного определения (= `function`), но в прикладном коде для такой возможности сложно придумать полезные кейсы.

В общем, см. [WindowTimers.`setTimeout`](https://developer.mozilla.org/ru/docs/Web/API/setTimeout#%D1%81%D0%B8%D0%BD%D1%82%D0%B0%D0%BA%D1%81%D0%B8%D1%81):

```diff
- timeoutId = setTimeout(() => callback.apply(this, rest), timeoutDelay);
+ timeoutId = setTimeout(callback, timeoutDelay, ...rest);
```

2022-11-13 22:29 UTC, AlexMasterov commented on js/form.js
> +    if (evt.key && evt.key !== 'Escape') {
```diff
- if (evt.key && evt.key !== 'Escape') {
+ if (evt?.key !== 'Escape') {
```

2022-11-13 22:30 UTC, merged